name: Continous Integration and Deployement

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 11 🦴
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Setup .NET6 🦴
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Check out code 
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
    
      - name: Start Posgresql 
        run: |
          docker run --name db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_DB=whmappertest -p 5432:5432 -d postgres

      - name: Sleep for 5 seconds 
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Restore dependencies
        run: dotnet restore 

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Install SonarCloud scanners
        run: |
          dotnet tool install --global dotnet-sonarscanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       #   ConnectionStrings__DefaultConnection: "server=localhost;port=5432;database=whmappertest;User Id=postgres;Password=mysecretpassword"
        run: |
          dotnet-sonarscanner begin /k:"pfh59_eve-whmapper" /o:"pfh59" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build WHMapper -c Release --no-restore
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    #    run: |
    #      dotnet-sonarscanner begin /k:"pfh59_eve-whmapper" /o:"pfh59" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
    #      dotnet build WHMapper -c Release --no-restore
    #      dotnet test WHMapper.Tests -c Release
    #      dotnet publish WHMapper -c release -o ./out
    #      dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      
      - name: Build app 🚀
        run: dotnet build WHMapper -c Release --no-restore

      - name: Run automated test 🧪
        env:
          ConnectionStrings_DefaultConnection: "server=localhost;port=5432;database=whmappertest;User Id=postgres;Password=mysecretpassword"
        run: dotnet test WHMapper.Tests -c Release
      
      - name: Publish app 📑
        run: dotnet publish WHMapper -c release -o ./out

        

      





