name: Continous Integration and Deployement

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 
        uses: actions/checkout@v3
      
      - name: Setup .NET6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build app
        run: dotnet build -c Release --no-restore

        

      





